version: '3.3'
services:
 db:
   image: postgres:15
   environment:
     POSTGRES_DB: pedidos
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres   
   ports:
     - "5433:5432"
   volumes: 
     - pgdata:/var/lib/postgresql/data

 app:
   build: .
   depends_on: 
     - db 
   environment:
     DB_HOST: db
     DB_NAME: pedidos
     DB_USER: postgres
     DB_PASS: postgres
     DB_PORT: 5432
    
volumes:
 pgdata: